// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUiXr1UDwrqgtefJV8T4TDkzp_TFC7lhw',
    appId: '1:538675078690:web:23b9c8e072b043db794c7b',
    messagingSenderId: '538675078690',
    projectId: 'eneo-chat',
    authDomain: 'eneo-chat.firebaseapp.com',
    storageBucket: 'eneo-chat.firebasestorage.app',
    measurementId: 'G-E1HN3MXQW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzc2wRu1eoCuojd51SGOnAOtKZZHQ13kQ',
    appId: '1:538675078690:android:1dfab1abf369a19b794c7b',
    messagingSenderId: '538675078690',
    projectId: 'eneo-chat',
    storageBucket: 'eneo-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-lMt6_F30BGKSK091kJTVoTsc82h_NZo',
    appId: '1:538675078690:ios:555daf02919766d2794c7b',
    messagingSenderId: '538675078690',
    projectId: 'eneo-chat',
    storageBucket: 'eneo-chat.firebasestorage.app',
    iosBundleId: 'com.example.eneoAiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-lMt6_F30BGKSK091kJTVoTsc82h_NZo',
    appId: '1:538675078690:ios:555daf02919766d2794c7b',
    messagingSenderId: '538675078690',
    projectId: 'eneo-chat',
    storageBucket: 'eneo-chat.firebasestorage.app',
    iosBundleId: 'com.example.eneoAiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUiXr1UDwrqgtefJV8T4TDkzp_TFC7lhw',
    appId: '1:538675078690:web:5b547006b603a2db794c7b',
    messagingSenderId: '538675078690',
    projectId: 'eneo-chat',
    authDomain: 'eneo-chat.firebaseapp.com',
    storageBucket: 'eneo-chat.firebasestorage.app',
    measurementId: 'G-RL0D8J0RV7',
  );
}
